class DataNotFoundError(Exception):
    pass

class AlreadyExistError(Exception):
    pass